var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/index.config.js
var index_config_exports = {};
__export(index_config_exports, {
  default: () => index_config_default
});
module.exports = __toCommonJS(index_config_exports);
var index_config_default = {
  ali: {
    token: "",
    token280: "token280"
  },
  quark: {
    cookie: ""
  },
  uc: {
    cookie: "cookie",
    token: "token",
    ut: "ut"
  },
  y115: {
    cookie: ""
  },
  baidu: {
    cookie: ""
  },
  muou: {
    url: ""
  },
  wogg: {
    url: ""
  },
  leijing: {
    url: ""
  },
  tgsou: {
    tgPic: false,
    count: 0,
    url: "",
    channelUsername: ""
  },
  tgchannel: {},
  sites: {
    list: []
  },
  pans: {
    list: []
  },
  danmu: {
    urls: [
      { address: "https://fjj0417.dpdns.org/87654321", name: "默认1" },
      { address: "https://dm.stardm.us.kg:443/87654321", name: "默认2" },
      { address: "https://danmu.xyzd.eu.org/87654321", name: "默认3" },
      { address: "https://danmu.14812910.xyz/87654321", name: "默认4" }
    ],
    autoPush: true
  },
  t4: {list: [
    {name: "独播库",
      address: "http://zhangqun1818.serv00.net:6628/?spider=独播库"},
    {name: "电视丨直播",
      address: "http://zhangqun1818.serv00.net/zh/2242.php"},
    {name: "人人丨JS",
      address: "http://zhangqun1818.serv00.net:6628/?spider=人人影视"},
     {name: "爱奇艺丨影视",
      address: "https://iqiyizyapi.com/api.php/provide/vod"},
    {name: "吉米丨影视",
      address: "https://catbox.n13.club/t9/jimi.php"},
    {name: "克隆丨影视",
      address: "http://zhangqun1818.serv00.net/klhj.php"},
    {name: "恋鱼丨影视",
      address: "https://catbox.n13.club/t9/lianyu.php"},
    {name: "星之阁丨影视",
      address: "https://catbox.n13.club/t9/xingzhige.php"},
    {name: "专享丨影视",
      address: "http://sspa8.top:99/php/专享.php"},
    {name: "小鸭丨影视",
      address: "http://zhangqun1818.serv00.net:5052/?sp=小鸭子看看"},
    {name: "努努丨JS",
      address: "http://zhangqun1818.serv00.net:5052/?sp=努努影院"},
    {name: "酷我丨JS",
      address: "http://sspa8.top:99/php/酷我.php"},
    {name: "听书丨JS",
      address: "http://sspa8.top:99/api.php?id=%E8%87%B3%E8%87%BB%E5%BD%B1%E9%9F%B3&uid=suisui"},
    {name: "cctv丨PY",
      address: "https://zhangqun1818.serv00.net/cctv.php"},
    {name: "兔小贝丨少儿",
      address: "http://zhangqun1818.serv00.net:6628/?spider=兔小贝"},
    {name: "清风丨PHP",
      address: "http://sspa8.top:8100/php/清风.php"},
    {name: "红果丨短剧",
      address: "https://catbox.n13.club/ai/红果短剧.php"},
    {name: "旺旺丨短剧",
      address: "http://zhangqun1818.serv00.net/ww.php"},
    {name: "淘片丨影视",
      address: "https://www.taopianzy.com/cjapi/mc/vod/json.html"},
    {name: "CK丨影视",
      address: "https://ckzy.me/api.php/provide/vod"},
    {name: "如意丨影视",
      address: "http://cj.rycjapi.com/api.php/provide/vod/"},
    {name: "番茄丨影视",
      address: "https://fqzy.me/api.php/provide/vod/?ac=list"},
    {name: "香蕉丨影视",
      address: "https://www.xiangjiaozyw.com/api.php/provide/vod/"},
    {name: "爱瓜丨影视",
      address: "http://zhangqun1818.serv00.net:5052/?sp=爱瓜影视"},
    {name: "3Q丨影视",
      address: "http://zhangqun1818.serv00.net:6628/?spider=3q影视"},
    {name: "Emby丨WebDAV",
      address: "http://zhangqun1818.serv00.net:6628/?spider=emby"},
    {name: "凤凰丨FM",
      address: "http://zhangqun1818.serv00.net:6628/?spider=凤凰fm"},
    {name: "采集丨聚合",
      address: "http://zhangqun1818.serv00.net/cj/cjjh.php"},
    {name: "瓜子丨影视",
      address: "https://catbox.n13.club/ai/瓜子影视.php"},
    {name: "JS丨聚合",
      address: "http://zhangqun1818.serv00.net/js.php"},
    {name: "139丨听书",
      address: "http://zhangqun1818.serv00.net:5052/?sp=139fm多分类"},
    {name: "PY丨聚合",
      address: "http://zhangqun1818.serv00.net/py.php"},
    {name: "PHP丨聚合",
      address: "http://zhangqun1818.serv00.net/php.php"},
    {name: "鲨鱼丨采集",
      address: "https://shayuzy5.com/api.php/provide/vod/"},
    {name: "推特丨爬虫",
      address: "http://zhangqun1818.serv00.net:5052/?sp=推特"},
    {name: "九区丨爬虫",
      address: "http://zhangqun1818.serv00.net:5052/?sp=九个区"},
    {name: "人剧丨爬虫",
      address: "http://sspa8.top:99/api.php?id=rr&uid=suisui"},
    {name: "UAA丨爬虫",
      address: "http://zhangqun1818.serv00.net:5052/?sp=uaa有声"},
    {name: "爆料丨糖心",
      address: "https://caicai.us.kg/糖心次元.php"},
    {name: "免等丨云盘",
      address: "http://sspa8.top:99/api.php?id=yt&uid=suisui"},
    {name: "EPO丨爬虫",
      address: "http://zhangqun1818.serv00.net:5052/?sp=epo"}
]},
 cms: {list: [
{name: "麻花丨采集",
address: "https://19q.cc/api.php/provide/vod"},
{name: "杏吧丨采集",
address: "https://xingba111.com/api.php/provide/vod/?ac=list"},
{name: "越南丨采集",
address: "https://vnzyz.com/api.php/provide/vod"},
{name: "猫眼丨采集",
address: "https://api.maoyanapi.top/api.php/provide/vod"},
{name: "细胞丨采集",
address: "https://www.xxibaozyw.com/api.php/provide/vod"},
{name: "15丨采集",
address: "https://155api.com/api.php/provide/vod"},
{name: "91AV丨采集",
address: "https://91av.cyou/api.php/provide/vod"},
{name: "小鸡丨采集",
address: "https://api.xiaojizy.live/provide/vod"},
{name: "大奶丨采集",
address: "https://apidanaizi.com/api.php/provide/vod"},
{name: "豆豆丨采集",
address: "https://api.douapi.cc/api.php/provide/vod/"},
{name: "色屁丨采集",
address: "https://www.saobi2.com/api.php/provide/vod/"},
{name: "黑料丨采集",
address: "https://heiliaozyapi.com/api.php/provide/vod/"},
{name: "仓库丨采集",
address: "https://hsckzy888.com/api.php/provide/vod/from/hsckm3u8/at/json"},
{name: "玉兔丨采集",
address: "https://apiyutu.com/api.php/provide/vod"},
{name: "奶香丨采集",
address: "https://naixxzy.com/api.php/provide/vod"},
{name: "乐播丨采集",
address: "https://lbapi9.com/api.php/provide/vod"},
{name: "JKUN丨采集",
address: "https://jkunzyapi.com/api.php/provide/vod"},
{name: "聚合丨采集",
address: "http://150.109.94.44:1112/api.php/provide/vod/"},
{name: "桃花丨采集",
address: "https://thzy1.me/api.php/provide/vod/"},
{name: "百花丨采集",
address: "https://bhziyuan.com/api.php/provide/vod/"},
{name: "无水丨采集",
address: "https://api.wsyzy.net/api.php/provide/vod/"},
{name: "奥斯卡丨影视",
address: "https://aosikazy4.com/api.php/provide/vod"},
{name: "八天丨采集",
address: "https://8day.icu/api.php/provide/vod/"},
{name: "优优丨采集",
address: "https://www.yyzywcj.com/api.php/provide/vod/"},
{name: "番号丨采集",
address: "http://fhapi9.com/api.php/provide/vod"},
{name: "辣椒丨采集",
address: "https://apilj.com/api.php/provide/vod"},
{name: "湿园丨采集",
address: "https://xxavs.com/api.php/provide/vod"},
{name: "森林丨采集",
address: "https://slapibf.com/api.php/provide/vod"},
{name: "丝袜丨采集",
address: "https://siwazyw.tv/api.php/provide/vod/"},
{name: "色猫丨采集",
address: "https://caiji.semaozy.net/inc/apijson_vod.php"},
{name: "蛋蛋丨采集",
address: "https://ddmf.net/api.php/provide/vod/"},
{name: "老色丨采集",
address: "https://apilsbzy1.com/api.php/provide/vod/"},
{name: "百万丨采集",
address: "https://api.bwzyz.com/api.php/provide/vod/"},
{name: "漫道丨采集",
address: "https://www.mandao.cc/api.php/provide/vod/"},
]},

  pansou: {
    api_urls: "https://so.252035.xyz",
    channels: "",
    plugins: "",
    cloud_types: "aliyun,quark,uc,115,123,tianyi,baidu",
    include: "",
    exclude: "",
    count: 20,
    pancheck: "https://pancheck.banye.tech:7777",
    pancheck_enabled: false
  },
  emby: [
    {
      name: "embysim服",
      server: "http://192.168.50.119:8096",
      username: "emby",
      password: "1234",
      deviceName: "Hills Windows",
      client: "Hills Windows",
      clientVersion: "0.2.3",
      enablePlaybackReport: true
      // 播放进度上报EMBY服务器
    },
    {
      name: "示例",
      server: "",
      username: "",
      password: "",
      deviceName: "",
      client: "",
      clientVersion: "",
      enablePlaybackReport: false
    }
  ],
  bilibili: {
    cookie: "",
    classes: ""
  },
  alist: [
    {
      name: "🐉神族九帝",
      server: "https://alist.shenzjd.com"
    },
    {
      name: "💢repl",
      server: "https://ali.liucn.repl.co"
    }
  ],
  color: [
    {
      light: {
        bg: "https://i2.100024.xyz/2024/01/13/pptcej.webp",
        bgMask: "0x50ffffff",
        primary: "0xff446732",
        onPrimary: "0xffffffff",
        primaryContainer: "0xffc5efab",
        onPrimaryContainer: "0xff072100",
        secondary: "0xff55624c",
        onSecondary: "0xffffffff",
        secondaryContainer: "0xffd9e7cb",
        onSecondaryContainer: "0xff131f0d",
        tertiary: "0xff386666",
        onTertiary: "0xffffffff",
        tertiaryContainer: "0xffbbebec",
        onTertiaryContainer: "0xff002020",
        error: "0xffba1a1a",
        onError: "0xffffffff",
        errorContainer: "0xffffdad6",
        onErrorContainer: "0xff410002",
        background: "0xfff8faf0",
        onBackground: "0xff191d16",
        surface: "0xfff8faf0",
        onSurface: "0xff191d16",
        surfaceVariant: "0xffe0e4d6",
        onSurfaceVariant: "0xff191d16",
        inverseSurface: "0xff2e312b",
        inverseOnSurface: "0xfff0f2e7",
        outline: "0xff74796d",
        outlineVariant: "0xffc3c8bb",
        shadow: "0xff000000",
        scrim: "0xff000000",
        inversePrimary: "0xffaad291",
        surfaceTint: "0xff446732"
      },
      dark: {
        bg: "https://i2.100024.xyz/2024/01/13/pptg3z.webp",
        bgMask: "0x50000000",
        primary: "0xffaad291",
        onPrimary: "0xff173807",
        primaryContainer: "0xff2d4f1c",
        onPrimaryContainer: "0xffc5efab",
        secondary: "0xffbdcbb0",
        onSecondary: "0xff283420",
        secondaryContainer: "0xff3e4a35",
        onSecondaryContainer: "0xffd9e7cb",
        tertiary: "0xffa0cfcf",
        onTertiary: "0xff003738",
        tertiaryContainer: "0xff1e4e4e",
        onTertiaryContainer: "0xffbbebec",
        error: "0xffffb4ab",
        onError: "0xff690005",
        errorContainer: "0xff93000a",
        onErrorContainer: "0xffffdad6",
        background: "0xff11140e",
        onBackground: "0xffe1e4d9",
        surface: "0xff11140e",
        onSurface: "0xffe1e4d9",
        surfaceVariant: "0xff43483e",
        onSurfaceVariant: "0xffe1e4d9",
        inverseSurface: "0xffe1e4d9",
        inverseOnSurface: "0xff2e312b",
        outline: "0xff8d9286",
        outlineVariant: "0xff43483e",
        shadow: "0xff000000",
        scrim: "0xff000000",
        inversePrimary: "0xff446732",
        surfaceTint: "0xffaad291"
      }
    },
    {
      light: {
        bg: "https://i2.100024.xyz/2024/01/13/pi2rpw.webp",
        bgMask: "0x50ffffff",
        primary: "0xff666014",
        onPrimary: "0xffffffff",
        primaryContainer: "0xffeee58c",
        onPrimaryContainer: "0xff1f1c00",
        secondary: "0xff625f42",
        onSecondary: "0xffffffff",
        secondaryContainer: "0xffe9e4be",
        onSecondaryContainer: "0xff1e1c05",
        tertiary: "0xff3f6654",
        onTertiary: "0xffffffff",
        tertiaryContainer: "0xffc1ecd5",
        onTertiaryContainer: "0xff002114",
        error: "0xffba1a1a",
        onError: "0xffffffff",
        errorContainer: "0xffffdad6",
        onErrorContainer: "0xff410002",
        background: "0xfffef9eb",
        onBackground: "0xff1d1c14",
        surface: "0xfffef9eb",
        onSurface: "0xff1d1c14",
        surfaceVariant: "0xffe7e3d0",
        onSurfaceVariant: "0xff1d1c14",
        inverseSurface: "0xff323128",
        inverseOnSurface: "0xfff5f1e3",
        outline: "0xff7a7768",
        outlineVariant: "0xffcbc7b5",
        shadow: "0xff000000",
        scrim: "0xff000000",
        inversePrimary: "0xffd1c973",
        surfaceTint: "0xff666014"
      },
      dark: {
        bg: "https://i2.100024.xyz/2024/01/13/pi2reo.webp",
        bgMask: "0x50000000",
        primary: "0xffd1c973",
        onPrimary: "0xff353100",
        primaryContainer: "0xff4d4800",
        onPrimaryContainer: "0xffeee58c",
        secondary: "0xffcdc8a3",
        onSecondary: "0xff333117",
        secondaryContainer: "0xff4a482c",
        onSecondaryContainer: "0xffe9e4be",
        tertiary: "0xffa6d0b9",
        onTertiary: "0xff0e3727",
        tertiaryContainer: "0xff274e3d",
        onTertiaryContainer: "0xffc1ecd5",
        error: "0xffffb4ab",
        onError: "0xff690005",
        errorContainer: "0xff93000a",
        onErrorContainer: "0xffffdad6",
        background: "0xff14140c",
        onBackground: "0xffe7e2d5",
        surface: "0xff14140c",
        onSurface: "0xffe7e2d5",
        surfaceVariant: "0xff49473a",
        onSurfaceVariant: "0xffe7e2d5",
        inverseSurface: "0xffe7e2d5",
        inverseOnSurface: "0xff323128",
        outline: "0xff949181",
        outlineVariant: "0xff49473a",
        shadow: "0xff000000",
        scrim: "0xff000000",
        inversePrimary: "0xff666014",
        surfaceTint: "0xffd1c973"
      }
    },
    {
      light: {
        bg: "https://i2.100024.xyz/2024/01/13/qrnuwt.webp",
        bgMask: "0x50ffffff",
        primary: "0xFF2B6C00",
        onPrimary: "0xFFFFFFFF",
        primaryContainer: "0xFFA6F779",
        onPrimaryContainer: "0xFF082100",
        secondary: "0xFF55624C",
        onSecondary: "0xFFFFFFFF",
        secondaryContainer: "0xFFD9E7CA",
        onSecondaryContainer: "0xFF131F0D",
        tertiary: "0xFF386666",
        onTertiary: "0xFFFFFFFF",
        tertiaryContainer: "0xFFBBEBEB",
        onTertiaryContainer: "0xFF002020",
        error: "0xFFBA1A1A",
        onError: "0xFFFFFFFF",
        errorContainer: "0xFFFFDAD6",
        onErrorContainer: "0xFF410002",
        background: "0xFFFDFDF5",
        onBackground: "0xFF1A1C18",
        surface: "0xFFFDFDF5",
        onSurface: "0xFF1A1C18",
        surfaceVariant: "0xFFE0E4D6",
        onSurfaceVariant: "0xFF1A1C18",
        inverseSurface: "0xFF2F312C",
        onInverseSurface: "0xFFF1F1EA",
        outline: "0xFF74796D",
        outlineVariant: "0xFFC3C8BB",
        shadow: "0xFF000000",
        scrim: "0xFF000000",
        inversePrimary: "0xFF8CDA60",
        surfaceTint: "0xFF2B6C00"
      },
      dark: {
        bg: "https://i2.100024.xyz/2024/01/13/qrc37o.webp",
        bgMask: "0x50000000",
        primary: "0xFF8CDA60",
        onPrimary: "0xFF133800",
        primaryContainer: "0xFF1F5100",
        onPrimaryContainer: "0xFFA6F779",
        secondary: "0xFFBDCBAF",
        onSecondary: "0xFF283420",
        secondaryContainer: "0xFF3E4A35",
        onSecondaryContainer: "0xFFD9E7CA",
        tertiary: "0xFFA0CFCF",
        onTertiary: "0xFF003737",
        tertiaryContainer: "0xFF1E4E4E",
        onTertiaryContainer: "0xFFBBEBEB",
        error: "0xFFFFB4AB",
        errorContainer: "0xFF93000A",
        onError: "0xFF690005",
        onErrorContainer: "0xFFFFDAD6",
        background: "0xFF1A1C18",
        onBackground: "0xFFE3E3DC",
        outline: "0xFF8D9286",
        onInverseSurface: "0xFF1A1C18",
        inverseSurface: "0xFFE3E3DC",
        inversePrimary: "0xFF2B6C00",
        shadow: "0xFF000000",
        surfaceTint: "0xFF8CDA60",
        outlineVariant: "0xFF43483E",
        scrim: "0xFF000000",
        surface: "0xFF1A1C18",
        onSurface: "0xFFC7C7C0",
        surfaceVariant: "0xFF43483E",
        onSurfaceVariant: "0xFFC7C7C0"
      }
    }
  ]
};
